### ISSUE TITLE
Can't see all space

### ISSUE THREAD

**Issue by TerrAcoHee** [ufe-pr/vitasensus#10]
sometimes space all miss, not only me, others open it without any space

![image](https://user-images.githubusercontent.com/48586082/180397074-895f5774-784b-4195-b3f2-2cfcabe3bceb.png)

**Comment by ufe-pr** [comment]
When I had this issue, the problem was that it wasn't able to connect to the WebSocket endpoint of testnet (https://buidl.vite.net/gvite/ws). I don't know if that's the same issue you had.
