### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by TerrAcoHee** [ufe-pr/vitasensus#13]
At the same time, I think the following functions need to be added, otherwise the project cannot be edited and it will be bad

1. Add Proposal threshold, Proposal threshold is the minimum number of tokens required to create a proposal.

2. Add Allow only admins to submit a proposal,
admins will be able to create proposals without being constrained by filters. You must add one address per line. Once enabled, only admins will be allowed to post proposals

3. When creating a project, the creation page needs to have the Admin option. The default address for creating a project is the administrator, and other addresses can be added as adminis.
As the Admin address, you can edit the information of the project, such as updating the logo, project description, modifying the Proposal threshold, etc.

4.  it's better if the owner can delete them

**Comment by ufe-pr** [comment]
All of these features have been implemented except the owner being able to delete the space.

Allowing the owner delete a space can cause complications where the owner just decides to nuke the space against the members' will.
