### ISSUE TITLE
cannot create proposals

### ISSUE THREAD

**Issue by TerrAcoHee** [ufe-pr/vitasensus#14]
When I set as below, Create proposal threshold >=1000

My other address has 5000vite but cannot create proposals

<img width="755" alt="image" src="https://user-images.githubusercontent.com/48586082/181205706-239bf6fc-9708-469f-b311-df8afbb5e7c6.png">

**Comment by ufe-pr** [comment]
Fixed. 

The amount to be transacted for the create proposal transaction wasn't being calculated properly in the app, hence the failure.
