### ISSUE TITLE
proposal fail

### ISSUE THREAD

**Issue by TerrAcoHee** [ufe-pr/vitasensus#4]
If I first enter the project space, click on the innovation proposal, fill in the information, and then log in, the proposal will fail to be created

<img width="942" alt="image" src="https://user-images.githubusercontent.com/48586082/180380718-3ca67c04-b86a-49c1-986f-edcece4e5ccd.png">

**Comment by ufe-pr** [comment]
I'm unable to reproduce this error following the steps you provided. Was there any other thing you did?
