### ISSUE TITLE
Search and filter functions

### ISSUE THREAD

**Issue by TerrAcoHee** [ufe-pr/vitasensus#8]
Search and filter functions are not available

![image](https://user-images.githubusercontent.com/48586082/180388020-f15d933b-f0d5-4632-be62-8d14707ba661.png)

**Comment by ufe-pr** [comment]
So for this, I removed the other filter functions and kept only the search.

The user's spaces already show up on the sidebar so it doesn't really make sense to have a filter for that again. They could just go to the space from the sidebar.

And sorting by name would be way too computationally expensive to combine with the search query considering that data is being fetched from a smart contract (excessive calls would be made to the smart contract just to achieve that properly).
