### ISSUE TITLE
space logo

### ISSUE THREAD

**Issue by TerrAcoHee** [ufe-pr/vitasensus#9]
By the way, what are the requirements for the link of the icon, I use this link, but the created project does not display the logo

https://reurl.cc/ZbabGV

**Comment by ufe-pr** [comment]
The link responds with an HTML page containing some js to take you to the content (it's not a 302 or 301 redirect response). Hence, the browser cannot parse that. 

You can use [Imgur](https://imgur.com/upload) to host the image if the actual image URL is longer than the allowed length.
